### ISSUE TITLE
Read config files with BuildStep.findAssets

### ISSUE THREAD

**Issue by kuhnroyal** [knaeckeKami/config_builder#1]
Just a quick hint after seeing the known issue and your code. You need to read the json files via `BuildStep.findAssets(Glob)` and not as plain file. Otherwise the build_runner can not watch the files.

**Comment by knaeckeKami** [comment]
Thank you so much!

This has left me slightly annoyed for a long time now, it was just never a high enough priority to fix it. 

But this looks easy to fix, I'll release an update soon.

**Comment by knaeckeKami** [comment]
Fixed in 1.0.0
